spring:
  cqfile:
    project: filedemo
    work-dir: temp
    cache: true
    temporary: true
    ftp:
      enable: false
    smb:
      enable: true
      url: 10.10.10.181
      username: weizc
      password: 789376152
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 100GB
